import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.*;

// Tests for RescueSystem: searching for rescue cases, unique rescue IDs and status updates through the menu.
// RescueSystem reads everything from its Scanner, reports back on System.out and keeps its list of cases
// private, so each test scripts the user's input up front and then checks what the system printed.
class RescueSystemTest {

    // Answers to every createRescue() prompt, in the order they are asked
    private static final String INJURED_LION =
            lines("1", "Leo", "Lion", "Kruger National Park", "Sipho", "5", "1000", "Fractured leg", "y", "2000");
    private static final String ORPHANED_ELEPHANT =
            lines("2", "Ellie", "Elephant", "Addo Elephant Park", "Thandi", "10", "500", "6", "300", "n");
    private static final String ENDANGERED_RHINO =
            lines("3", "Nandi", "Black Rhino", "Hluhluwe-iMfolozi Park", "Bongani", "3", "2000",
                    "Critically Endangered", "10000", "y");

    // Matches the confirmation createRescue() prints and captures the new case's ID
    private static final Pattern CREATED_ID = Pattern.compile("Rescue case #(\\d+) created");

    private final PrintStream originalOut = System.out;
    private final ByteArrayOutputStream printed = new ByteArrayOutputStream();

    @BeforeEach
    void capturePrintedOutput() {
        System.setOut(new PrintStream(printed, true));
    }

    @AfterEach
    void restorePrintedOutput() {
        System.setOut(originalOut);
    }

    // ---- Searching for an existing rescue case ----

    @Test
    void searchFindsEachRescueCaseByItsId() {
        RescueSystem system = systemWithInput(INJURED_LION, ORPHANED_ELEPHANT, ENDANGERED_RHINO,
                lines("2"), lines("1"), lines("3"));
        createRescues(system, 3);

        String result = search(system);
        assertContains("ORPHANED ANIMAL RESCUE - CASE #2", result);
        assertContains(RescueCase.formatLine("Species", "Elephant"), result);
        assertNotContains("CASE #1", result);
        assertNotContains("CASE #3", result);

        result = search(system);
        assertContains("INJURED ANIMAL RESCUE - CASE #1", result);
        assertContains(RescueCase.formatLine("Species", "Lion"), result);

        result = search(system);
        assertContains("ENDANGERED SPECIES RESCUE - CASE #3", result);
        assertContains(RescueCase.formatLine("Species", "Black Rhino"), result);
    }

    @Test
    void searchForAnIdThatDoesNotExistReportsNoMatch() {
        RescueSystem system = systemWithInput(INJURED_LION, lines("99"));
        createRescues(system, 1);

        String result = search(system);

        assertContains("No rescue case found with ID 99.", result);
        assertNotContains("CASE #", result);
    }

    @Test
    void searchWithNoRescueCasesReportsNoMatch() {
        RescueSystem system = systemWithInput(lines("1"));

        assertContains("No rescue case found with ID 1.", search(system));
    }

    @Test
    void searchKeepsAskingUntilAValidIdIsEntered() {
        // "abc" and "0" are rejected by the ID prompt before 1 is accepted
        RescueSystem system = systemWithInput(INJURED_LION, lines("abc", "0", "1"));
        createRescues(system, 1);

        String result = search(system);

        assertContains("Please enter a whole number greater than 0.", result);
        assertContains("INJURED ANIMAL RESCUE - CASE #1", result);
    }

    // ---- Preventing duplicate rescue case IDs ----
    // IDs are generated by the system rather than typed in by the user, so these tests check
    // that every new case is given an ID no other case already has.

    @Test
    void everyNewRescueCaseGetsADifferentId() {
        // The last two cases repeat earlier details, which must still not lead to a repeated ID
        RescueSystem system = systemWithInput(INJURED_LION, ORPHANED_ELEPHANT, ENDANGERED_RHINO,
                INJURED_LION, ORPHANED_ELEPHANT);

        for (int i = 0; i < 5; i++) {
            assertTrue(system.createRescue());
        }

        // Five different IDs, handed out in order
        assertEquals(List.of(1, 2, 3, 4, 5), createdIds(printed.toString()));
    }

    @Test
    void rescueCasesWithIdenticalDetailsCanEachBeFoundByTheirOwnId() {
        RescueSystem system = systemWithInput(INJURED_LION, INJURED_LION, lines("1"), lines("2"));
        createRescues(system, 2);

        assertContains("INJURED ANIMAL RESCUE - CASE #1", search(system));
        assertContains("INJURED ANIMAL RESCUE - CASE #2", search(system));
    }

    @Test
    void rejectedRescueTypeDoesNotUseUpAnId() {
        // 4 is not a valid rescue type, so nothing is created and the next case still gets ID 1
        RescueSystem system = systemWithInput(lines("4"), INJURED_LION, ORPHANED_ELEPHANT);

        assertFalse(system.createRescue());
        assertTrue(system.createRescue());
        assertTrue(system.createRescue());

        assertEquals(List.of(1, 2), createdIds(printed.toString()));
    }

    // ---- Rescue status updates through the menu ----

    @Test
    void newRescueCaseStartsAsPending() {
        RescueSystem system = systemWithInput(INJURED_LION, lines("1"));

        system.createRescue();

        assertContains("Rescue case #1 created with status Pending.", printed.toString());
        assertContains(statusLine(RescueStatus.PENDING), search(system));
    }

    @Test
    void updateStartsAndThenCompletesARescue() {
        RescueSystem system = systemWithInput(INJURED_LION,
                lines("1", "1"),   // update case 1: Start Rescue
                lines("1"),        // search case 1
                lines("1", "2"),   // update case 1: Complete Rescue
                lines("1"));       // search case 1
        createRescues(system, 1);

        assertContains("Rescue #1 started", update(system));
        assertContains(statusLine(RescueStatus.IN_PROGRESS), search(system));

        assertContains("Rescue #1 completed", update(system));
        assertContains(statusLine(RescueStatus.COMPLETED), search(system));
    }

    @Test
    void updateRefusesToCompleteARescueThatHasNotStarted() {
        RescueSystem system = systemWithInput(INJURED_LION, lines("1", "2"), lines("1"));
        createRescues(system, 1);

        assertContains("Rescue #1 cannot move from Pending to Completed.", update(system));
        assertContains(statusLine(RescueStatus.PENDING), search(system));
    }

    @Test
    void updateRefusesToStartARescueThatIsAlreadyInProgress() {
        RescueSystem system = systemWithInput(INJURED_LION, lines("1", "1"), lines("1", "1"), lines("1"));
        createRescues(system, 1);
        update(system);

        assertContains("Rescue #1 cannot move from In Progress to In Progress.", update(system));
        assertContains(statusLine(RescueStatus.IN_PROGRESS), search(system));
    }

    @Test
    void updateWithAnInvalidOptionLeavesTheStatusUnchanged() {
        RescueSystem system = systemWithInput(INJURED_LION, lines("1", "3"), lines("1"));
        createRescues(system, 1);

        assertContains("Invalid option. Rescue case was not updated.", update(system));
        assertContains(statusLine(RescueStatus.PENDING), search(system));
    }

    @Test
    void updateForAnIdThatDoesNotExistReportsNoMatch() {
        RescueSystem system = systemWithInput(INJURED_LION, lines("5"), lines("1"));
        createRescues(system, 1);

        String result = update(system);

        assertContains("No rescue case found with ID 5.", result);
        // It should stop there, without asking whether to start or complete the rescue
        assertNotContains("Current status", result);
        assertContains(statusLine(RescueStatus.PENDING), search(system));
    }

    // ---- Helpers ----

    // Joins lines into one block of input, as if the user typed each one and pressed Enter
    private static String lines(String... lines) {
        return String.join("\n", lines) + "\n";
    }

    // A RescueSystem that will read the given scripts, in order, as the user's input
    private static RescueSystem systemWithInput(String... scripts) {
        return new RescueSystem(new Scanner(String.join("", scripts)));
    }

    // Creates the given number of rescue cases, then clears what was printed so far
    private void createRescues(RescueSystem system, int count) {
        for (int i = 0; i < count; i++) {
            system.createRescue();
        }
        printed.reset();
    }

    // Runs one search and returns only what that search printed
    private String search(RescueSystem system) {
        printed.reset();
        system.searchRescueCase();
        return printed.toString();
    }

    // Runs one update and returns only what that update printed
    private String update(RescueSystem system) {
        printed.reset();
        system.updateRescueCase();
        return printed.toString();
    }

    // The "Current Status" line exactly as it appears in a case summary
    private static String statusLine(RescueStatus status) {
        return RescueCase.formatLine("Current Status", status);
    }

    // Pulls the ID out of every "Rescue case #N created" confirmation, in the order they were printed
    private static List<Integer> createdIds(String output) {
        List<Integer> ids = new ArrayList<>();
        Matcher matcher = CREATED_ID.matcher(output);

        while (matcher.find()) {
            ids.add(Integer.parseInt(matcher.group(1)));
        }

        return ids;
    }

    // On failure these show the full printed output, so it's easy to see what the system actually said
    private static void assertContains(String expected, String output) {
        assertTrue(output.contains(expected), () -> "Expected to find:\n" + expected + "\nin:\n" + output);
    }

    private static void assertNotContains(String unexpected, String output) {
        assertFalse(output.contains(unexpected), () -> "Did not expect to find:\n" + unexpected + "\nin:\n" + output);
    }
}
